Feat/master/autogeneration
codaxy/conductor-sharp pull request #177
Opened 2024-01-09 09:32 UTC by ognjenkatic

This PR is a major refactor of the client project. It switches over from hand written client code to semi auto generated (NSwag) to achieve full support for conductor API and make it easier to follow changes. There is a layer of abstraction in between the caller and the auto generated code that makes the method names a bit more meaningful.

We also took the opportunity to move to .Net6 and do some code changes to take advantage of some of the newer language features.

2024-01-11 14:58 UTC, boma96 requested changes
Some comments to consider

2024-01-12 21:14 UTC, ognjenkatic commented on src/ConductorSharp.Client/ConductorSharp.Client.csproj
> +    <PackageReference Include="System.Text.Json" Version="8.0.0" />
Nice catch, i believe we needed this before we migrated the project over to .net6, there was something missing in .netcore. Removed it now.

2024-01-12 21:14 UTC, ognjenkatic commented on src/ConductorSharp.Engine/ExecutionManager.cs
> +                await _taskManager.LogAsync(pollResponse.TaskId, exception.StackTrace, cancellationToken);
Added, however, note the comment i added above the calls.

2024-01-12 21:18 UTC, ognjenkatic commented
> @ognjenkatic Also can you put nswag file used to generate models and client into repository

This would be two files, as we split it into models and client file. Lets see if we like what we made and do some testing. If it works out, I will add them to the .sourcegen directory.

2024-01-16 10:12 UTC, boma96 approved these changes
We should test this parallel scenario before making stable release. In following days I plan to introduce some changes so after that we can do proper release

2024-01-16 19:46 UTC, boma96 requested changes
@ognjenkatic I just noticed that you used WorkflowTaskType instead of Type in Builders.
According to [docs](https://orkes.io/content/reference-docs/worker-task) `type` should be used. Also swagger file contains both `type` and `workflowTaskType` for some reason

2024-01-21 20:45 UTC, ognjenkatic commented
> @ognjenkatic I just noticed that you used WorkflowTaskType instead of Type in Builders. According to [docs](https://orkes.io/content/reference-docs/worker-task) `type` should be used. Also swagger file contains both `type` and `workflowTaskType` for some reason.

Conductor seems to allow setting workflow task type in two ways, either as a string `type` or enum `workflowTaskType`.

In the generated models `setWorkflowTaskType` is a non nullable enum, so if not set to actual task type explicitly on our end it will have the first enum value `SIMPLE`.
![image](https://github.com/codaxy/conductor-sharp/assets/44910579/5880cb00-d107-46ef-97fe-de3b10a4b4c0)

2024-01-23 12:02 UTC, ognjenkatic commented
Both string and enum values are now sent for type.

2024-01-23 12:03 UTC, merged