Terminate task
codaxy/conductor-sharp pull request #38
Opened 2022-08-25 12:13 UTC by boma96

Added support for terminate task

```
builder.AddTask(
                wf => wf.Terminate,
                wf => new() { TerminationStatus = TerminationStatus.Failed, WorkflowOutput = new { Property = "Test" } }
            );
```

2022-08-25 16:23 UTC, ognjenkatic requested changes
Just one suggestion

2022-08-26 06:54 UTC, boma96 commented on src/ConductorSharp.Engine/Model/TerminateTaskModel.cs
> +        public string TerminationStatus { get; set; }
terminationStatus input parameter must be constant (i.e. either COMPLETED or FAILED). Specifying this parameter as an output of some task is not allowed (Registration of workflow will fail).

2022-08-26 07:55 UTC, boma96 commented on src/ConductorSharp.Engine/Model/TerminateTaskModel.cs
> +        public string TerminationStatus { get; set; }
As for enum values, currently, they would be converted to numeric values. Newtonsoft serializer can be configured to serialize enum as a string but there is this line that prevents me from doing that.

```
  // TODO: Make this not required, as we want to allow the user to init client as he likes
  _restClient.UseNewtonsoftJson();
```

UseNetwonsoftJson method has an argument that allows us to configure serialization. Are we gonna remove this line as TODO comment says?

An alternative would be to detect these special enum constants in expression code and convert them manually.

2022-08-29 11:16 UTC, boma96 commented on src/ConductorSharp.Engine/Model/TerminateTaskModel.cs
> +        public string TerminationStatus { get; set; }
@ognjenkatic Replaced static class with an enum, added code which handles enum constants. Also added a way for the library user to specify how enums are mapped.

2022-09-02 13:03 UTC, ognjenkatic approved these changes
LGTM

2022-09-02 13:03 UTC, merged